"""Delivery gate: how a verified fix lands.

- AUTO_MERGE: fast-forward the fix branch into the deploy branch, restart the
  service to pick it up, resolve the incident, notify everywhere.
- DRAFT_PR: keep the branch, push if a remote exists, record a Markdown PR
  body as an incident event, and wait for the 1-click approve endpoint.

Push/PR-creation via git CLI only (no tokens stored); failures degrade to
'pending approval' with the branch preserved — never force, never delete.
"""
from __future__ import annotations

from pathlib import Path

from sqlalchemy.orm import Session

from app.core.logging import get_logger
from app.db.models import Incident, RemediationAction, Service
from app.engines import audit_engine, incident_engine, notification_engine, restart_manager
from app.engines.restart_manager import PROJECT_ROOT
from app.remediation import git_workspace
from app.utils.events import bus
from app.utils.time import utcnow

log = get_logger("delivery")


def pr_body(*, service_name: str, incident: Incident, root_cause: str,
            stack: str, test_results: str, diff_stat: str) -> str:
    return (
        f"## AeroOps auto-fix for {service_name}\n\n"
        f"**Incident:** #{incident.id} · **Severity:** {incident.severity}\n"
        f"**Root cause:** {root_cause}\n\n"
        f"### Crash\n```\n{stack[:1500]}\n```\n\n"
        f"### Verification\n```\n{test_results[:1500]}\n```\n\n"
        f"### Diff\n```\n{diff_stat[:1000]}\n```\n\n"
        f"_Generated by AeroOps. Approve & Deploy merges + restarts + verifies._\n")


async def deliver_merged(db: Session, ws, *, incident: Incident,
                         deploy_branch: str, test_results: str) -> bool:
    svc = incident.service
    ok, msg = await git_workspace.merge_fast_forward(ws, deploy_branch)
    action = RemediationAction(incident_id=incident.id, action_type="merge_fix",
                               source="automation",
                               status="succeeded" if ok else "failed",
                               params={"branch": ws.branch, "into": deploy_branch},
                               result=msg[:1000] if ok else "",
                               error="" if ok else msg[:1000],
                               started_at=utcnow(), completed_at=utcnow())
    db.add(action)
    db.flush()
    if not ok:
        incident_engine.add_event(db, incident.id, "MERGE_FAILED", msg[:500])
        return False
    incident_engine.add_event(db, incident.id, "MERGED", msg[:500])
    # restart so the running process picks up the merged fix, then verify.
    # stop-then-start (never idempotent start): the old process must die,
    # otherwise the merge deploys without ever taking effect.
    try:
        if svc.command:
            try:
                restart_manager.stop(svc.id)
            except Exception:
                pass
            pid = restart_manager.start(svc.id, svc.command, svc.working_directory,
                                        svc.env_config or {})
            incident_engine.add_event(db, incident.id, "REMEDIATION_EXECUTED",
                                      f"restarted after merge pid={pid}")
            healthy = await restart_manager.wait_healthy(
                lambda: _healthy(svc.id), attempts=3, interval=2, budget_sec=60,
                startup_grace_sec=3)
        else:
            healthy = True  # nothing running to reload (e.g. browser target)
    except Exception as exc:
        healthy = False
        incident_engine.add_event(db, incident.id, "RESTART_FAILED", str(exc)[:300])
    if healthy:
        incident.recovery_verified = True
        try:
            # legal path only: DIAGNOSED -> RECOVERING -> RESOLVED
            if incident.status not in ("RECOVERING",):
                try:
                    incident_engine.transition(db, incident, "RECOVERING",
                                               message="deploy live, verifying")
                except Exception:
                    pass
            incident_engine.transition(db, incident, "RESOLVED", message="fix merged + verified")
        except Exception:
            pass
        audit_engine.record(db, "INCIDENT_RESOLVED", service_id=svc.id,
                            incident_id=incident.id, actor="automation",
                            action="deliver_merged", result="ok")
    else:
        try:
            incident_engine.transition(db, incident, "FAILED", message="merged but unhealthy")
        except Exception:
            pass
    notification_engine.notify(
        db, f"Fix {'deployed' if healthy else 'merged, UNHEALTHY'} on {svc.name}",
        f"Incident #{incident.id}\nBranch merged into {deploy_branch}\n"
        f"Recovery: {'verified' if healthy else 'FAILED verification — look now'}",
        incident_id=incident.id)
    db.commit()
    await bus.publish("service.recovered" if healthy else "notification",
                      {"incident_id": incident.id, "service_id": svc.id})
    return healthy


async def deliver_draft_pr(db: Session, ws, *, incident: Incident,
                           root_cause: str, stack: str, test_results: str,
                           diff_stat: str) -> str:
    """Push branch if possible; always record the PR pack for 1-click approval."""
    svc = incident.service
    code, remotes = await git_workspace._git(ws.repo, "remote")
    pushed = False
    push_note = "no git remote configured"
    if code == 0 and remotes.strip():
        code, out = await git_workspace._git(ws.repo, "push", "-u", "origin", ws.branch)
        pushed = code == 0
        push_note = "pushed to origin" if pushed else f"push failed: {out[-200:]}"
    body = pr_body(service_name=svc.name, incident=incident, root_cause=root_cause,
                   stack=stack, test_results=test_results, diff_stat=diff_stat)
    action = RemediationAction(incident_id=incident.id, action_type="open_draft_pr",
                               source="automation",
                               status="succeeded" if pushed else "pending",
                               params={"branch": ws.branch, "pushed": pushed},
                               result=(push_note + "\n\n" + body)[:2000],
                               started_at=utcnow(), completed_at=utcnow())
    db.add(action)
    db.flush()
    incident_engine.add_event(db, incident.id, "DRAFT_PR",
                              f"{push_note}; branch {ws.branch} awaiting approval")
    audit_engine.record(db, "REMEDIATION_EXECUTED", service_id=svc.id,
                        incident_id=incident.id, actor="automation",
                        action="open_draft_pr", result="pending" if not pushed else "pushed")
    notification_engine.notify(
        db, f"Fix ready to approve on {svc.name}",
        f"Incident #{incident.id}\n{root_cause}\nBranch: {ws.branch}\n{push_note}\n"
        f"Approve: POST /api/delivery/approve {{\"incident_id\": {incident.id}}}",
        incident_id=incident.id)
    db.commit()
    await bus.publish("notification", {"incident_id": incident.id})
    return body


async def _healthy(service_id: int) -> bool:
    from app.db.database import SessionLocal
    from app.engines import health_engine
    db: Session = SessionLocal()
    try:
        service = db.get(Service, service_id)
        if not service:
            return False
        return bool((await health_engine.check(service))["ok"])
    finally:
        db.close()


def workspace_for(service_workdir: str) -> Path:
    return (PROJECT_ROOT / (service_workdir or ".")).resolve()
