"""service repo tracking

Revision ID: 02bd6c816f98
Revises: bc69957694c2
Create Date: 2026-09-11 10:25:46.570441
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '02bd6c816f98'
down_revision: str | None = 'bc69957694c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('repo_path_or_url', sa.String(length=500), server_default='', nullable=False))
    op.add_column('services', sa.Column('git_token_enc', sa.String(length=1000), server_default='', nullable=False))
    op.add_column('services', sa.Column('target_branch', sa.String(length=120), server_default='', nullable=False))
    op.add_column('services', sa.Column('workspace_frontend', sa.String(length=200), server_default='', nullable=False))
    op.add_column('services', sa.Column('workspace_backend', sa.String(length=200), server_default='', nullable=False))
    op.add_column('services', sa.Column('test_command', sa.String(length=500), server_default='', nullable=False))
    op.add_column('services', sa.Column('remediation_policy', sa.String(length=20), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'remediation_policy')
    op.drop_column('services', 'test_command')
    op.drop_column('services', 'workspace_backend')
    op.drop_column('services', 'workspace_frontend')
    op.drop_column('services', 'target_branch')
    op.drop_column('services', 'git_token_enc')
    op.drop_column('services', 'repo_path_or_url')
    # ### end Alembic commands ###
