"""diagnoses model column

Revision ID: 42c1fad32818
Revises: a8a851149b1c
Create Date: 2026-09-06 02:07:56.672287
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42c1fad32818'
down_revision: str | None = 'a8a851149b1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('model', sa.String(length=80), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'model')
    # ### end Alembic commands ###
