"""incident fingerprint

Revision ID: 8f62269df463
Revises: 8da56776f83e
Create Date: 2026-09-08 22:09:27.841714
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8f62269df463'
down_revision: str | None = '8da56776f83e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('fingerprint', sa.String(length=32), server_default='', nullable=False))
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_column('incidents', 'fingerprint')
    # ### end Alembic commands ###
