"""service expected content

Revision ID: a301d2bcc2d8
Revises: 8f62269df463
Create Date: 2026-09-08 22:39:18.251466
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a301d2bcc2d8'
down_revision: str | None = '8f62269df463'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('expected_content', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'expected_content')
    # ### end Alembic commands ###
