"""service delivery policy

Revision ID: bc69957694c2
Revises: a301d2bcc2d8
Create Date: 2026-09-09 23:02:09.658290
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bc69957694c2'
down_revision: str | None = 'a301d2bcc2d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('policy_mode', sa.String(length=20), server_default='DRAFT_PR', nullable=False))
    op.add_column('services', sa.Column('deploy_branch', sa.String(length=120), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'deploy_branch')
    op.drop_column('services', 'policy_mode')
    # ### end Alembic commands ###
